import { db } from '../lib/db';
import { nflDraft } from '../schema';

const picks = [
  // Round 1
  { round: 1, pick: 1,   roundPick: 1,  playerName: 'Cam Ward',              position: 'QB',  nflTeam: 'Tennessee Titans',       college: 'Miami (FL)' },
  { round: 1, pick: 2,   roundPick: 2,  playerName: 'Travis Hunter',         position: 'CB',  nflTeam: 'Jacksonville Jaguars',   college: 'Colorado' },
  { round: 1, pick: 3,   roundPick: 3,  playerName: 'Abdul Carter',          position: 'DE',  nflTeam: 'New York Giants',        college: 'Penn State' },
  { round: 1, pick: 4,   roundPick: 4,  playerName: 'Will Campbell',         position: 'OT',  nflTeam: 'New England Patriots',   college: 'LSU' },
  { round: 1, pick: 5,   roundPick: 5,  playerName: 'Mason Graham',          position: 'DT',  nflTeam: 'Cleveland Browns',       college: 'Michigan' },
  { round: 1, pick: 6,   roundPick: 6,  playerName: 'Ashton Jeanty',         position: 'RB',  nflTeam: 'Las Vegas Raiders',      college: 'Boise State' },
  { round: 1, pick: 7,   roundPick: 7,  playerName: 'Armand Membou',         position: 'OT',  nflTeam: 'New York Jets',          college: 'Missouri' },
  { round: 1, pick: 8,   roundPick: 8,  playerName: 'Tetairoa McMillan',     position: 'WR',  nflTeam: 'Carolina Panthers',      college: 'Arizona' },
  { round: 1, pick: 9,   roundPick: 9,  playerName: 'Kelvin Banks Jr.',      position: 'OT',  nflTeam: 'New Orleans Saints',     college: 'Texas' },
  { round: 1, pick: 10,  roundPick: 10, playerName: 'Colston Loveland',      position: 'TE',  nflTeam: 'Chicago Bears',          college: 'Michigan' },
  { round: 1, pick: 11,  roundPick: 11, playerName: 'Mykel Williams',        position: 'DE',  nflTeam: 'San Francisco 49ers',    college: 'Georgia' },
  { round: 1, pick: 12,  roundPick: 12, playerName: 'Tyler Booker',          position: 'G',   nflTeam: 'Dallas Cowboys',         college: 'Alabama' },
  { round: 1, pick: 13,  roundPick: 13, playerName: 'Kenneth Grant',         position: 'DT',  nflTeam: 'Miami Dolphins',         college: 'Michigan' },
  { round: 1, pick: 14,  roundPick: 14, playerName: 'Tyler Warren',          position: 'TE',  nflTeam: 'Indianapolis Colts',     college: 'Penn State' },
  { round: 1, pick: 15,  roundPick: 15, playerName: 'Jalon Walker',          position: 'OLB', nflTeam: 'Atlanta Falcons',        college: 'Georgia' },
  { round: 1, pick: 16,  roundPick: 16, playerName: 'Walter Nolen',          position: 'DT',  nflTeam: 'Arizona Cardinals',      college: 'Ole Miss' },
  { round: 1, pick: 17,  roundPick: 17, playerName: 'Shemar Stewart',        position: 'DE',  nflTeam: 'Cincinnati Bengals',     college: 'Texas A&M' },
  { round: 1, pick: 18,  roundPick: 18, playerName: 'Grey Zabel',            position: 'G',   nflTeam: 'Seattle Seahawks',       college: 'North Dakota State' },
  { round: 1, pick: 19,  roundPick: 19, playerName: 'Emeka Egbuka',          position: 'WR',  nflTeam: 'Tampa Bay Buccaneers',   college: 'Ohio State' },
  { round: 1, pick: 20,  roundPick: 20, playerName: 'Jahdae Barron',         position: 'CB',  nflTeam: 'Denver Broncos',         college: 'Texas' },
  { round: 1, pick: 21,  roundPick: 21, playerName: 'Derrick Harmon',        position: 'DT',  nflTeam: 'Pittsburgh Steelers',    college: 'Oregon' },
  { round: 1, pick: 22,  roundPick: 22, playerName: 'Omarion Hampton',       position: 'RB',  nflTeam: 'Los Angeles Chargers',   college: 'North Carolina' },
  { round: 1, pick: 23,  roundPick: 23, playerName: 'Matthew Golden',        position: 'WR',  nflTeam: 'Green Bay Packers',      college: 'Texas' },
  { round: 1, pick: 24,  roundPick: 24, playerName: 'Donovan Jackson',       position: 'G',   nflTeam: 'Minnesota Vikings',      college: 'Ohio State' },
  { round: 1, pick: 25,  roundPick: 25, playerName: 'Jaxson Dart',           position: 'QB',  nflTeam: 'New York Giants',        college: 'Ole Miss' },
  { round: 1, pick: 26,  roundPick: 26, playerName: 'James Pearce Jr.',      position: 'DE',  nflTeam: 'Atlanta Falcons',        college: 'Tennessee' },
  { round: 1, pick: 27,  roundPick: 27, playerName: 'Malaki Starks',         position: 'S',   nflTeam: 'Baltimore Ravens',       college: 'Georgia' },
  { round: 1, pick: 28,  roundPick: 28, playerName: 'Tyleik Williams',       position: 'DT',  nflTeam: 'Detroit Lions',          college: 'Ohio State' },
  { round: 1, pick: 29,  roundPick: 29, playerName: 'Josh Conerly Jr.',      position: 'OT',  nflTeam: 'Washington Commanders',  college: 'Oregon' },
  { round: 1, pick: 30,  roundPick: 30, playerName: 'Maxwell Hairston',      position: 'CB',  nflTeam: 'Buffalo Bills',          college: 'Kentucky' },
  { round: 1, pick: 31,  roundPick: 31, playerName: 'Jihaad Campbell',       position: 'LB',  nflTeam: 'Philadelphia Eagles',    college: 'Alabama' },
  { round: 1, pick: 32,  roundPick: 32, playerName: 'Josh Simmons',          position: 'OT',  nflTeam: 'Kansas City Chiefs',     college: 'Ohio State' },
  // Round 2
  { round: 2, pick: 33,  roundPick: 1,  playerName: 'Carson Schwesinger',    position: 'LB',  nflTeam: 'Cleveland Browns',       college: 'UCLA' },
  { round: 2, pick: 34,  roundPick: 2,  playerName: 'Jayden Higgins',        position: 'WR',  nflTeam: 'Houston Texans',         college: 'Iowa State' },
  { round: 2, pick: 35,  roundPick: 3,  playerName: 'Nick Emmanwori',        position: 'S',   nflTeam: 'Seattle Seahawks',       college: 'South Carolina' },
  { round: 2, pick: 36,  roundPick: 4,  playerName: 'Quinshon Judkins',      position: 'RB',  nflTeam: 'Cleveland Browns',       college: 'Ohio State' },
  { round: 2, pick: 37,  roundPick: 5,  playerName: 'Jonah Savaiinaea',      position: 'G',   nflTeam: 'Miami Dolphins',         college: 'Arizona' },
  { round: 2, pick: 38,  roundPick: 6,  playerName: 'TreVeyon Henderson',    position: 'RB',  nflTeam: 'New England Patriots',   college: 'Ohio State' },
  { round: 2, pick: 39,  roundPick: 7,  playerName: 'Luther Burden III',     position: 'WR',  nflTeam: 'Chicago Bears',          college: 'Missouri' },
  { round: 2, pick: 40,  roundPick: 8,  playerName: 'Tyler Shough',          position: 'QB',  nflTeam: 'New Orleans Saints',     college: 'Louisville' },
  { round: 2, pick: 41,  roundPick: 9,  playerName: 'TJ Sanders',            position: 'DT',  nflTeam: 'Buffalo Bills',          college: 'South Carolina' },
  { round: 2, pick: 42,  roundPick: 10, playerName: 'Mason Taylor',          position: 'TE',  nflTeam: 'New York Jets',          college: 'LSU' },
  { round: 2, pick: 43,  roundPick: 11, playerName: 'Alfred Collins',        position: 'DT',  nflTeam: 'San Francisco 49ers',    college: 'Texas' },
  { round: 2, pick: 44,  roundPick: 12, playerName: 'Donovan Ezeiruaku',     position: 'DE',  nflTeam: 'Dallas Cowboys',         college: 'Boston College' },
  { round: 2, pick: 45,  roundPick: 13, playerName: 'JT Tuimoloau',          position: 'DE',  nflTeam: 'Indianapolis Colts',     college: 'Ohio State' },
  { round: 2, pick: 46,  roundPick: 14, playerName: 'Terrance Ferguson',     position: 'TE',  nflTeam: 'Los Angeles Rams',       college: 'Oregon' },
  { round: 2, pick: 47,  roundPick: 15, playerName: 'Will Johnson',          position: 'CB',  nflTeam: 'Arizona Cardinals',      college: 'Michigan' },
  { round: 2, pick: 48,  roundPick: 16, playerName: 'Aireontae Ersery',      position: 'OT',  nflTeam: 'Houston Texans',         college: 'Minnesota' },
  { round: 2, pick: 49,  roundPick: 17, playerName: 'Demetrius Knight',      position: 'LB',  nflTeam: 'Cincinnati Bengals',     college: 'South Carolina' },
  { round: 2, pick: 50,  roundPick: 18, playerName: 'Elijah Arroyo',         position: 'TE',  nflTeam: 'Seattle Seahawks',       college: 'Miami (FL)' },
  { round: 2, pick: 51,  roundPick: 19, playerName: 'Nic Scourton',          position: 'DE',  nflTeam: 'Carolina Panthers',      college: 'Texas A&M' },
  { round: 2, pick: 52,  roundPick: 20, playerName: 'Oluwafemi Oladejo',     position: 'DE',  nflTeam: 'Tennessee Titans',       college: 'UCLA' },
  { round: 2, pick: 53,  roundPick: 21, playerName: 'Benjamin Morrison',     position: 'CB',  nflTeam: 'Tampa Bay Buccaneers',   college: 'Notre Dame' },
  { round: 2, pick: 54,  roundPick: 22, playerName: 'Anthony Belton',        position: 'OT',  nflTeam: 'Green Bay Packers',      college: 'NC State' },
  { round: 2, pick: 55,  roundPick: 23, playerName: 'Tre Harris',            position: 'WR',  nflTeam: 'Los Angeles Chargers',   college: 'Ole Miss' },
  { round: 2, pick: 56,  roundPick: 24, playerName: 'Ozzy Trapilo',          position: 'OT',  nflTeam: 'Chicago Bears',          college: 'Boston College' },
  { round: 2, pick: 57,  roundPick: 25, playerName: 'Tate Ratledge',         position: 'G',   nflTeam: 'Detroit Lions',          college: 'Georgia' },
  { round: 2, pick: 58,  roundPick: 26, playerName: 'Jack Bech',             position: 'WR',  nflTeam: 'Las Vegas Raiders',      college: 'TCU' },
  { round: 2, pick: 59,  roundPick: 27, playerName: 'Mike Green',            position: 'LB',  nflTeam: 'Baltimore Ravens',       college: 'Marshall' },
  { round: 2, pick: 60,  roundPick: 28, playerName: 'RJ Harvey',             position: 'RB',  nflTeam: 'Denver Broncos',         college: 'UCF' },
  { round: 2, pick: 61,  roundPick: 29, playerName: 'Trey Amos',             position: 'CB',  nflTeam: 'Washington Commanders',  college: 'Ole Miss' },
  { round: 2, pick: 62,  roundPick: 30, playerName: 'Shemar Turner',         position: 'DT',  nflTeam: 'Chicago Bears',          college: 'Texas A&M' },
  { round: 2, pick: 63,  roundPick: 31, playerName: 'Omarr Norman-Lott',     position: 'DT',  nflTeam: 'Kansas City Chiefs',     college: 'Tennessee' },
  { round: 2, pick: 64,  roundPick: 32, playerName: 'Andrew Mukuba',         position: 'S',   nflTeam: 'Philadelphia Eagles',    college: 'Texas' },
  // Round 3
  { round: 3, pick: 65,  roundPick: 1,  playerName: 'Darius Alexander',      position: 'DT',  nflTeam: 'New York Giants',        college: 'Toledo' },
  { round: 3, pick: 66,  roundPick: 2,  playerName: 'Ashton Gillotte',       position: 'DE',  nflTeam: 'Kansas City Chiefs',     college: 'Louisville' },
  { round: 3, pick: 67,  roundPick: 3,  playerName: 'Harold Fannin Jr.',     position: 'TE',  nflTeam: 'Cleveland Browns',       college: 'Bowling Green' },
  { round: 3, pick: 68,  roundPick: 4,  playerName: 'Darien Porter',         position: 'CB',  nflTeam: 'Las Vegas Raiders',      college: 'Iowa State' },
  { round: 3, pick: 69,  roundPick: 5,  playerName: 'Kyle Williams',         position: 'WR',  nflTeam: 'New England Patriots',   college: 'Washington State' },
  { round: 3, pick: 70,  roundPick: 6,  playerName: 'Isaac TeSlaa',          position: 'WR',  nflTeam: 'Detroit Lions',          college: 'Arkansas' },
  { round: 3, pick: 71,  roundPick: 7,  playerName: 'Vernon Broughton',      position: 'DT',  nflTeam: 'New Orleans Saints',     college: 'Texas' },
  { round: 3, pick: 72,  roundPick: 8,  playerName: 'Landon Jackson',        position: 'DE',  nflTeam: 'Buffalo Bills',          college: 'Arkansas' },
  { round: 3, pick: 73,  roundPick: 9,  playerName: "Azareye'h Thomas",      position: 'CB',  nflTeam: 'New York Jets',          college: 'Florida State' },
  { round: 3, pick: 74,  roundPick: 10, playerName: 'Pat Bryant',            position: 'WR',  nflTeam: 'Denver Broncos',         college: 'Illinois' },
  { round: 3, pick: 75,  roundPick: 11, playerName: 'Nick Martin',           position: 'LB',  nflTeam: 'San Francisco 49ers',    college: 'Oklahoma State' },
  { round: 3, pick: 76,  roundPick: 12, playerName: 'Shavon Revel',          position: 'CB',  nflTeam: 'Dallas Cowboys',         college: 'East Carolina' },
  { round: 3, pick: 77,  roundPick: 13, playerName: 'Princely Umanmielen',   position: 'DE',  nflTeam: 'Carolina Panthers',      college: 'Ole Miss' },
  { round: 3, pick: 78,  roundPick: 14, playerName: 'Jordan Burch',          position: 'DE',  nflTeam: 'Arizona Cardinals',      college: 'Oregon' },
  { round: 3, pick: 79,  roundPick: 15, playerName: 'Jaylin Noel',           position: 'WR',  nflTeam: 'Houston Texans',         college: 'Iowa State' },
  { round: 3, pick: 80,  roundPick: 16, playerName: 'Justin Walley',         position: 'CB',  nflTeam: 'Indianapolis Colts',     college: 'Minnesota' },
  { round: 3, pick: 81,  roundPick: 17, playerName: 'Dylan Fairchild',       position: 'G',   nflTeam: 'Cincinnati Bengals',     college: 'Georgia' },
  { round: 3, pick: 82,  roundPick: 18, playerName: 'Kevin Winston Jr.',     position: 'S',   nflTeam: 'Tennessee Titans',       college: 'Penn State' },
  { round: 3, pick: 83,  roundPick: 19, playerName: 'Kaleb Johnson',         position: 'RB',  nflTeam: 'Pittsburgh Steelers',    college: 'Iowa' },
  { round: 3, pick: 84,  roundPick: 20, playerName: 'Jacob Parrish',         position: 'CB',  nflTeam: 'Tampa Bay Buccaneers',   college: 'Kansas State' },
  { round: 3, pick: 85,  roundPick: 21, playerName: 'Nohl Williams',         position: 'CB',  nflTeam: 'Kansas City Chiefs',     college: 'California' },
  { round: 3, pick: 86,  roundPick: 22, playerName: 'Jamaree Caldwell',      position: 'DT',  nflTeam: 'Los Angeles Chargers',   college: 'Oregon' },
  { round: 3, pick: 87,  roundPick: 23, playerName: 'Savion Williams',       position: 'WR',  nflTeam: 'Green Bay Packers',      college: 'TCU' },
  { round: 3, pick: 88,  roundPick: 24, playerName: 'Caleb Ransaw',          position: 'CB',  nflTeam: 'Jacksonville Jaguars',   college: 'Tulane' },
  { round: 3, pick: 89,  roundPick: 25, playerName: 'Wyatt Milum',           position: 'G',   nflTeam: 'Jacksonville Jaguars',   college: 'West Virginia' },
  { round: 3, pick: 90,  roundPick: 26, playerName: 'Josaiah Stewart',       position: 'DE',  nflTeam: 'Los Angeles Rams',       college: 'Michigan' },
  { round: 3, pick: 91,  roundPick: 27, playerName: 'Emery Jones Jr.',       position: 'OT',  nflTeam: 'Baltimore Ravens',       college: 'LSU' },
  { round: 3, pick: 92,  roundPick: 28, playerName: 'Jalen Milroe',          position: 'QB',  nflTeam: 'Seattle Seahawks',       college: 'Alabama' },
  { round: 3, pick: 93,  roundPick: 29, playerName: 'Jonas Sanker',          position: 'S',   nflTeam: 'New Orleans Saints',     college: 'Virginia' },
  { round: 3, pick: 94,  roundPick: 30, playerName: 'Dillon Gabriel',        position: 'QB',  nflTeam: 'Cleveland Browns',       college: 'Oregon' },
  { round: 3, pick: 95,  roundPick: 31, playerName: 'Jared Wilson',          position: 'C',   nflTeam: 'New England Patriots',   college: 'Georgia' },
  { round: 3, pick: 96,  roundPick: 32, playerName: 'Xavier Watts',          position: 'S',   nflTeam: 'Atlanta Falcons',        college: 'Notre Dame' },
  { round: 3, pick: 97,  roundPick: 33, playerName: 'Jaylin Smith',          position: 'CB',  nflTeam: 'Houston Texans',         college: 'USC' },
  { round: 3, pick: 98,  roundPick: 34, playerName: 'Caleb Rogers',          position: 'G',   nflTeam: 'Las Vegas Raiders',      college: 'Texas Tech' },
  { round: 3, pick: 99,  roundPick: 35, playerName: 'Charles Grant',         position: 'OT',  nflTeam: 'Las Vegas Raiders',      college: 'William & Mary' },
  { round: 3, pick: 100, roundPick: 36, playerName: 'Upton Stout',           position: 'CB',  nflTeam: 'San Francisco 49ers',    college: 'Western Kentucky' },
  { round: 3, pick: 101, roundPick: 37, playerName: "Sai'vion Jones",        position: 'DE',  nflTeam: 'Denver Broncos',         college: 'LSU' },
  { round: 3, pick: 102, roundPick: 38, playerName: 'Tai Felton',            position: 'WR',  nflTeam: 'Minnesota Vikings',      college: 'Maryland' },
  // Round 4
  { round: 4, pick: 103, roundPick: 1,  playerName: 'Chimere Dike',          position: 'WR',  nflTeam: 'Tennessee Titans',       college: 'Florida' },
  { round: 4, pick: 104, roundPick: 2,  playerName: 'Bhayshul Tuten',        position: 'RB',  nflTeam: 'Jacksonville Jaguars',   college: 'Virginia Tech' },
  { round: 4, pick: 105, roundPick: 3,  playerName: 'Cam Skattebo',          position: 'RB',  nflTeam: 'New York Giants',        college: 'Arizona State' },
  { round: 4, pick: 106, roundPick: 4,  playerName: 'Craig Woodson',         position: 'S',   nflTeam: 'New England Patriots',   college: 'California' },
  { round: 4, pick: 107, roundPick: 5,  playerName: 'Jack Kiser',            position: 'LB',  nflTeam: 'Jacksonville Jaguars',   college: 'Notre Dame' },
  { round: 4, pick: 108, roundPick: 6,  playerName: "Dont'e Thornton",       position: 'WR',  nflTeam: 'Las Vegas Raiders',      college: 'Tennessee' },
  { round: 4, pick: 109, roundPick: 7,  playerName: 'Deone Walker',          position: 'DT',  nflTeam: 'Buffalo Bills',          college: 'Kentucky' },
  { round: 4, pick: 110, roundPick: 8,  playerName: 'Arian Smith',           position: 'WR',  nflTeam: 'New York Jets',          college: 'Georgia' },
  { round: 4, pick: 111, roundPick: 9,  playerName: 'Ty Robinson',           position: 'DT',  nflTeam: 'Philadelphia Eagles',    college: 'Nebraska' },
  { round: 4, pick: 112, roundPick: 10, playerName: 'Danny Stutsman',        position: 'LB',  nflTeam: 'New Orleans Saints',     college: 'Oklahoma' },
  { round: 4, pick: 113, roundPick: 11, playerName: 'CJ West',               position: 'DT',  nflTeam: 'San Francisco 49ers',    college: 'Indiana' },
  { round: 4, pick: 114, roundPick: 12, playerName: 'Trevor Etienne',        position: 'RB',  nflTeam: 'Carolina Panthers',      college: 'Georgia' },
  { round: 4, pick: 115, roundPick: 13, playerName: 'Cody Simon',            position: 'LB',  nflTeam: 'Arizona Cardinals',      college: 'Ohio State' },
  { round: 4, pick: 116, roundPick: 14, playerName: 'Woody Marks',           position: 'RB',  nflTeam: 'Houston Texans',         college: 'USC' },
  { round: 4, pick: 117, roundPick: 15, playerName: 'Jarquez Hunter',        position: 'RB',  nflTeam: 'Los Angeles Rams',       college: 'Auburn' },
  { round: 4, pick: 118, roundPick: 16, playerName: 'Billy Bowman Jr.',      position: 'S',   nflTeam: 'Atlanta Falcons',        college: 'Oklahoma' },
  { round: 4, pick: 119, roundPick: 17, playerName: 'Barrett Carter',        position: 'LB',  nflTeam: 'Cincinnati Bengals',     college: 'Clemson' },
  { round: 4, pick: 120, roundPick: 18, playerName: 'Gunnar Helm',           position: 'TE',  nflTeam: 'Tennessee Titans',       college: 'Texas' },
  { round: 4, pick: 121, roundPick: 19, playerName: 'David Walker',          position: 'LB',  nflTeam: 'Tampa Bay Buccaneers',   college: 'Central Arkansas' },
  { round: 4, pick: 122, roundPick: 20, playerName: 'Lathan Ransom',         position: 'S',   nflTeam: 'Carolina Panthers',      college: 'Ohio State' },
  { round: 4, pick: 123, roundPick: 21, playerName: 'Jack Sawyer',           position: 'DE',  nflTeam: 'Pittsburgh Steelers',    college: 'Ohio State' },
  { round: 4, pick: 124, roundPick: 22, playerName: 'Barryn Sorrell',        position: 'DE',  nflTeam: 'Green Bay Packers',      college: 'Texas' },
  { round: 4, pick: 125, roundPick: 23, playerName: 'Kyle Kennard',          position: 'LB',  nflTeam: 'Los Angeles Chargers',   college: 'South Carolina' },
  { round: 4, pick: 126, roundPick: 24, playerName: 'Dylan Sampson',         position: 'RB',  nflTeam: 'Cleveland Browns',       college: 'Tennessee' },
  { round: 4, pick: 127, roundPick: 25, playerName: 'Jalen Travis',          position: 'OT',  nflTeam: 'Indianapolis Colts',     college: 'Iowa State' },
  { round: 4, pick: 128, roundPick: 26, playerName: 'Jaylin Lane',           position: 'WR',  nflTeam: 'Washington Commanders',  college: 'Virginia Tech' },
  { round: 4, pick: 129, roundPick: 27, playerName: 'Teddye Buchanan',       position: 'LB',  nflTeam: 'Baltimore Ravens',       college: 'California' },
  { round: 4, pick: 130, roundPick: 28, playerName: 'Malachi Moore',         position: 'S',   nflTeam: 'New York Jets',          college: 'Alabama' },
  { round: 4, pick: 131, roundPick: 29, playerName: 'Quincy Riley',          position: 'CB',  nflTeam: 'New Orleans Saints',     college: 'Louisville' },
  { round: 4, pick: 132, roundPick: 30, playerName: 'Ruben Hyppolite II',    position: 'LB',  nflTeam: 'Chicago Bears',          college: 'Maryland' },
  { round: 4, pick: 133, roundPick: 31, playerName: 'Jalen Royals',          position: 'WR',  nflTeam: 'Kansas City Chiefs',     college: 'Utah State' },
  { round: 4, pick: 134, roundPick: 32, playerName: 'Que Robinson',          position: 'LB',  nflTeam: 'Denver Broncos',         college: 'Alabama' },
  { round: 4, pick: 135, roundPick: 33, playerName: 'Tonka Hemingway',       position: 'DT',  nflTeam: 'Las Vegas Raiders',      college: 'South Carolina' },
  { round: 4, pick: 136, roundPick: 34, playerName: 'Elic Ayomanor',         position: 'WR',  nflTeam: 'Tennessee Titans',       college: 'Stanford' },
  { round: 4, pick: 137, roundPick: 35, playerName: 'Joshua Farmer',         position: 'DT',  nflTeam: 'New England Patriots',   college: 'Florida State' },
  { round: 4, pick: 138, roundPick: 36, playerName: 'Jordan Watkins',        position: 'WR',  nflTeam: 'San Francisco 49ers',    college: 'Ole Miss' },
  // Round 5
  { round: 5, pick: 139, roundPick: 1,  playerName: 'Tyrion Ingram-Dawkins', position: 'DE',  nflTeam: 'Minnesota Vikings',      college: 'Georgia' },
  { round: 5, pick: 140, roundPick: 2,  playerName: 'Cam Jackson',           position: 'DT',  nflTeam: 'Carolina Panthers',      college: 'Florida' },
  { round: 5, pick: 141, roundPick: 3,  playerName: 'Carson Vinson',         position: 'OT',  nflTeam: 'Baltimore Ravens',       college: 'Alabama A&M' },
  { round: 5, pick: 142, roundPick: 4,  playerName: 'Rylie Mills',           position: 'DT',  nflTeam: 'Seattle Seahawks',       college: 'Notre Dame' },
  { round: 5, pick: 143, roundPick: 5,  playerName: 'Jordan Phillips',       position: 'DT',  nflTeam: 'Miami Dolphins',         college: 'Maryland' },
  { round: 5, pick: 144, roundPick: 6,  playerName: 'Shedeur Sanders',       position: 'QB',  nflTeam: 'Cleveland Browns',       college: 'Colorado' },
  { round: 5, pick: 145, roundPick: 7,  playerName: 'Mac McWilliams',        position: 'CB',  nflTeam: 'Philadelphia Eagles',    college: 'UCF' },
  { round: 5, pick: 146, roundPick: 8,  playerName: 'Bradyn Swinson',        position: 'DE',  nflTeam: 'New England Patriots',   college: 'LSU' },
  { round: 5, pick: 147, roundPick: 9,  playerName: 'Jordan James',          position: 'RB',  nflTeam: 'San Francisco 49ers',    college: 'Oregon' },
  { round: 5, pick: 148, roundPick: 10, playerName: 'Ty Hamilton',           position: 'DT',  nflTeam: 'Los Angeles Rams',       college: 'Ohio State' },
  { round: 5, pick: 149, roundPick: 11, playerName: 'Jaydon Blue',           position: 'RB',  nflTeam: 'Dallas Cowboys',         college: 'Texas' },
  { round: 5, pick: 150, roundPick: 12, playerName: 'Jason Marshall Jr.',    position: 'CB',  nflTeam: 'Miami Dolphins',         college: 'Florida' },
  { round: 5, pick: 151, roundPick: 13, playerName: 'DJ Giddens',            position: 'RB',  nflTeam: 'Indianapolis Colts',     college: 'Kansas State' },
  { round: 5, pick: 152, roundPick: 14, playerName: 'Shemar James',          position: 'LB',  nflTeam: 'Dallas Cowboys',         college: 'Florida' },
  { round: 5, pick: 153, roundPick: 15, playerName: 'Jalen Rivers',          position: 'G',   nflTeam: 'Cincinnati Bengals',     college: 'Miami (FL)' },
  { round: 5, pick: 154, roundPick: 16, playerName: 'Marcus Mbow',           position: 'G',   nflTeam: 'New York Giants',        college: 'Purdue' },
  { round: 5, pick: 155, roundPick: 17, playerName: 'Dante Trader Jr.',      position: 'S',   nflTeam: 'Miami Dolphins',         college: 'Maryland' },
  { round: 5, pick: 156, roundPick: 18, playerName: 'Jeffrey Bassa',         position: 'LB',  nflTeam: 'Kansas City Chiefs',     college: 'Oregon' },
  { round: 5, pick: 157, roundPick: 19, playerName: 'Elijah Roberts',        position: 'DE',  nflTeam: 'Tampa Bay Buccaneers',   college: 'SMU' },
  { round: 5, pick: 158, roundPick: 20, playerName: 'KeAndre Lambert-Smith', position: 'WR',  nflTeam: 'Los Angeles Chargers',   college: 'Auburn' },
  { round: 5, pick: 159, roundPick: 21, playerName: 'Collin Oliver',         position: 'LB',  nflTeam: 'Green Bay Packers',      college: 'Oklahoma State' },
  { round: 5, pick: 160, roundPick: 22, playerName: 'Marques Sigle',         position: 'S',   nflTeam: 'San Francisco 49ers',    college: 'Kansas State' },
  { round: 5, pick: 161, roundPick: 23, playerName: 'Smael Mondon Jr.',      position: 'LB',  nflTeam: 'Philadelphia Eagles',    college: 'Georgia' },
  { round: 5, pick: 162, roundPick: 24, playerName: 'Francisco Mauigoa',     position: 'LB',  nflTeam: 'New York Jets',          college: 'Miami (FL)' },
  { round: 5, pick: 163, roundPick: 25, playerName: 'Mitchell Evans',        position: 'TE',  nflTeam: 'Carolina Panthers',      college: 'Notre Dame' },
  { round: 5, pick: 164, roundPick: 26, playerName: 'Yahya Black',           position: 'DT',  nflTeam: 'Pittsburgh Steelers',    college: 'Iowa' },
  { round: 5, pick: 165, roundPick: 27, playerName: 'Oronde Gadsden II',     position: 'TE',  nflTeam: 'Los Angeles Chargers',   college: 'Syracuse' },
  { round: 5, pick: 166, roundPick: 28, playerName: 'Tory Horton',           position: 'WR',  nflTeam: 'Seattle Seahawks',       college: 'Colorado State' },
  { round: 5, pick: 167, roundPick: 29, playerName: 'Jackson Slater',        position: 'G',   nflTeam: 'Tennessee Titans',       college: 'Sacramento State' },
  { round: 5, pick: 168, roundPick: 30, playerName: 'Drew Kendall',          position: 'C',   nflTeam: 'Philadelphia Eagles',    college: 'Boston College' },
  { round: 5, pick: 169, roundPick: 31, playerName: 'Zah Frazier',           position: 'CB',  nflTeam: 'Chicago Bears',          college: 'UTSA' },
  { round: 5, pick: 170, roundPick: 32, playerName: 'Jordan Hancock',        position: 'CB',  nflTeam: 'Buffalo Bills',          college: 'Ohio State' },
  { round: 5, pick: 171, roundPick: 33, playerName: 'Miles Frazier',         position: 'G',   nflTeam: 'Detroit Lions',          college: 'LSU' },
  { round: 5, pick: 172, roundPick: 34, playerName: 'Chris Paul Jr.',        position: 'LB',  nflTeam: 'Los Angeles Rams',       college: 'Ole Miss' },
  { round: 5, pick: 173, roundPick: 35, playerName: 'Jackson Hawes',         position: 'TE',  nflTeam: 'Buffalo Bills',          college: 'Georgia Tech' },
  { round: 5, pick: 174, roundPick: 36, playerName: 'Denzel Burke',          position: 'CB',  nflTeam: 'Arizona Cardinals',      college: 'Ohio State' },
  { round: 5, pick: 175, roundPick: 37, playerName: 'Robbie Ouzts',          position: 'FB',  nflTeam: 'Seattle Seahawks',       college: 'Alabama' },
  { round: 5, pick: 176, roundPick: 38, playerName: 'Tyler Baron',           position: 'DE',  nflTeam: 'New York Jets',          college: 'Miami (FL)' },
  // Round 6
  { round: 6, pick: 177, roundPick: 1,  playerName: 'Dorian Strong',         position: 'CB',  nflTeam: 'Buffalo Bills',          college: 'Virginia Tech' },
  { round: 6, pick: 178, roundPick: 2,  playerName: 'Bilhal Kone',           position: 'CB',  nflTeam: 'Baltimore Ravens',       college: 'Western Michigan' },
  { round: 6, pick: 179, roundPick: 3,  playerName: 'Ollie Gordon II',       position: 'RB',  nflTeam: 'Miami Dolphins',         college: 'Oklahoma State' },
  { round: 6, pick: 180, roundPick: 4,  playerName: 'JJ Pegues',             position: 'DT',  nflTeam: 'Las Vegas Raiders',      college: 'Ole Miss' },
  { round: 6, pick: 181, roundPick: 5,  playerName: 'Kyle McCord',           position: 'QB',  nflTeam: 'Philadelphia Eagles',    college: 'Syracuse' },
  { round: 6, pick: 182, roundPick: 6,  playerName: 'Andres Borregales',     position: 'K',   nflTeam: 'New England Patriots',   college: 'Miami (FL)' },
  { round: 6, pick: 183, roundPick: 7,  playerName: 'Marcus Harris',         position: 'CB',  nflTeam: 'Tennessee Titans',       college: 'California' },
  { round: 6, pick: 184, roundPick: 8,  playerName: 'Devin Neal',            position: 'RB',  nflTeam: 'New Orleans Saints',     college: 'Kansas' },
  { round: 6, pick: 185, roundPick: 9,  playerName: 'Will Howard',           position: 'QB',  nflTeam: 'Pittsburgh Steelers',    college: 'Ohio State' },
  { round: 6, pick: 186, roundPick: 10, playerName: 'Tyler Loop',            position: 'K',   nflTeam: 'Baltimore Ravens',       college: 'Arizona' },
  { round: 6, pick: 187, roundPick: 11, playerName: 'Jaylen Reed',           position: 'S',   nflTeam: 'Houston Texans',         college: 'Penn State' },
  { round: 6, pick: 188, roundPick: 12, playerName: 'Kalel Mullings',        position: 'RB',  nflTeam: 'Tennessee Titans',       college: 'Michigan' },
  { round: 6, pick: 189, roundPick: 13, playerName: 'Riley Leonard',         position: 'QB',  nflTeam: 'Indianapolis Colts',     college: 'Notre Dame' },
  { round: 6, pick: 190, roundPick: 14, playerName: 'Tim Smith',             position: 'DT',  nflTeam: 'Indianapolis Colts',     college: 'Alabama' },
  { round: 6, pick: 191, roundPick: 15, playerName: 'Myles Hinton',          position: 'OT',  nflTeam: 'Philadelphia Eagles',    college: 'Michigan' },
  { round: 6, pick: 192, roundPick: 16, playerName: 'Bryce Cabeldue',        position: 'G',   nflTeam: 'Seattle Seahawks',       college: 'Kansas' },
  { round: 6, pick: 193, roundPick: 17, playerName: 'Tahj Brooks',           position: 'RB',  nflTeam: 'Cincinnati Bengals',     college: 'Texas Tech' },
  { round: 6, pick: 194, roundPick: 18, playerName: 'Jalen McLeod',          position: 'LB',  nflTeam: 'Jacksonville Jaguars',   college: 'Auburn' },
  { round: 6, pick: 195, roundPick: 19, playerName: 'Luke Newman',           position: 'G',   nflTeam: 'Chicago Bears',          college: 'Michigan State' },
  { round: 6, pick: 196, roundPick: 20, playerName: 'Ahmed Hassanein',       position: 'DE',  nflTeam: 'Detroit Lions',          college: 'Boise State' },
  { round: 6, pick: 197, roundPick: 21, playerName: 'Graham Mertz',          position: 'QB',  nflTeam: 'Houston Texans',         college: 'Florida' },
  { round: 6, pick: 198, roundPick: 22, playerName: 'Warren Brinson',        position: 'DT',  nflTeam: 'Green Bay Packers',      college: 'Georgia' },
  { round: 6, pick: 199, roundPick: 23, playerName: 'Branson Taylor',        position: 'OT',  nflTeam: 'Los Angeles Chargers',   college: 'Pittsburgh' },
  { round: 6, pick: 200, roundPick: 24, playerName: 'Rayuan Lane III',       position: 'S',   nflTeam: 'Jacksonville Jaguars',   college: 'Navy' },
  { round: 6, pick: 201, roundPick: 25, playerName: 'Kobe King',             position: 'LB',  nflTeam: 'Minnesota Vikings',      college: 'Penn State' },
  { round: 6, pick: 202, roundPick: 26, playerName: 'Gavin Bartholomew',     position: 'TE',  nflTeam: 'Minnesota Vikings',      college: 'Pittsburgh' },
  { round: 6, pick: 203, roundPick: 27, playerName: 'LaJohntay Wester',      position: 'WR',  nflTeam: 'Baltimore Ravens',       college: 'Colorado' },
  { round: 6, pick: 204, roundPick: 28, playerName: 'Ajani Cornelius',       position: 'OT',  nflTeam: 'Dallas Cowboys',         college: 'Oregon' },
  { round: 6, pick: 205, roundPick: 29, playerName: 'Kain Medrano',          position: 'LB',  nflTeam: 'Washington Commanders',  college: 'UCLA' },
  { round: 6, pick: 206, roundPick: 30, playerName: 'Chase Lundt',           position: 'OT',  nflTeam: 'Buffalo Bills',          college: 'UConn' },
  { round: 6, pick: 207, roundPick: 31, playerName: 'Cameron Williams',      position: 'T',   nflTeam: 'Philadelphia Eagles',    college: 'Texas' },
];

async function main() {
  console.log(`Seeding ${picks.length} 2025 NFL draft picks...`);

  await db.delete(nflDraft).execute();

  const rows = picks.map(p => ({ year: 2025, ...p }));
  await db.insert(nflDraft).values(rows);

  console.log('Done.');
  process.exit(0);
}

main().catch(e => { console.error(e); process.exit(1); });
